### ISSUE TITLE
Does passing $pickset to Chance.js work?

### ISSUE THREAD

**Issue by kcfgl** [rueckstiess/mgeneratejs#13]
Awesome library, thank you for building this!

I'm trying to leverage the pickset helper on Chance.js to generate an array of unique items from a list.  I originally was using $choose but i need the values to be non-repeating. 

I'm trying to get the code right but getting tripped up on how to pass the array of values like this (and other ways):
`{"$pickset": {["alpha", "bravo", "charlie", "delta", "echo"], 3}}`

But it keeps generating errors like this:
`undefined:15
        {"$pickset": {["alpha", "bravo", "charlie", "delta", "echo"], 3}}
                      ^
SyntaxError: Unexpected token [ in JSON at position 682`

And this is doesn't error out, but it doesn't work either:
`{"$pickset": ["alpha", "bravo", "charlie", "delta", "echo", 3]} => [{"$undefined":true}]`

Any thoughts on how I should be setting this up to effectively pass over to Chance? I'm sure I'm doing something wrong. Or how to leverage $choose to generate list of uniques?

Thanks.

**Comment by kevinadi** [comment]
We just released `mgeneratejs` version 0.5.0 that includes the `$pickset` feature:

```
$ mgeneratejs '{"numbers": {"$pickset": {"array": ["red", "green", "blue"], "quantity": 2}}}'
{"numbers":["red","green"]}
```

Hope it's useful.
