### ISSUE TITLE
$pickset  example gives :[{"$undefined":true}]}

### ISSUE THREAD

**Issue by niccottrell** [rueckstiess/mgeneratejs#28]
The example in the README 
```js
{"color": {"$pickset": {"array": ["green", "red", "blue"], "quantity": 2}}}
``` 
gives 
```js
{"color":[{"$undefined":true}]}
```

I seem to be running version 0.4.1

**Comment by rueckstiess** [comment]
Hi, `$pickset` was introduced in version 0.5.0. Could you update to the latest version (currently 0.5.1) and try again? 

You can do that with `npm update -g mgeneratejs`.

**Comment by niccottrell** [comment]
Not sure why, but update was ignored. However `npm install -g mgeneratejs` worked!
